const guest = document.querySelector("#guest-2")
console.log(guest)
//const guestByClass = document.querySelector(".guest")
//console.log(guestByClass)
const guestByClassAll = document.querySelectorAll(".guest")
console.log(guestByClassAll)